In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
gdp_df = pd.read_csv('../data/gdp_percapita.csv')

In [3]:
gdp_df.head(6)

Country or Area  Year        Value  Value Footnotes
0     Afghanistan  2018  2190.240321              NaN
1     Afghanistan  2017  2202.570851              NaN
2     Afghanistan  2016  2200.764487              NaN
3     Afghanistan  2015  2212.750899              NaN
4     Afghanistan  2014  2249.253738              NaN
5     Afghanistan  2013  2264.317575              NaN

In [4]:
internet_df = pd.read_csv('../data/internet_use.csv', error_bad_lines=False)

b'Skipping line 4675: expected 4 fields, saw 6\n'


In [5]:
internet_df.head(6)

Country or Area  Year     Value  Value Footnotes
0     Afghanistan  2014  6.390000              NaN
1     Afghanistan  2013  5.900000              NaN
2     Afghanistan  2012  5.454545              NaN
3     Afghanistan  2011  5.000000              NaN
4     Afghanistan  2010  4.000000              NaN
5     Afghanistan  2009  3.550000              NaN

In [6]:
gdp_df.shape

(6608, 4)

gdp_df has 6608 rows and 4 columns

In [7]:
internet_df.shape

(4675, 4)

internet_df has 4675 rows and 4 columns

In [8]:
gdp_df.dtypes

Country or Area     object
Year                object
Value              float64
Value Footnotes    float64
dtype: object

In [9]:
internet_df.dtypes

Country or Area     object
Year                object
Value              float64
Value Footnotes    float64
dtype: object

In [10]:
gdp_df.tail(10)

Country or Area                                      Year        Value  \
6598        Zimbabwe                                      1997  3580.048793   
6599        Zimbabwe                                      1996  3520.430146   
6600        Zimbabwe                                      1995  3226.413930   
6601        Zimbabwe                                      1994  3263.934978   
6602        Zimbabwe                                      1993  3033.504852   
6603        Zimbabwe                                      1992  3054.889178   
6604        Zimbabwe                                      1991  3426.598094   
6605        Zimbabwe                                      1990  3324.348171   
6606   footnoteSeqID                                  Footnote          NaN   
6607               2  Excludes South Sudan after July 9, 2011.          NaN   

      Value Footnotes  
6598              NaN  
6599              NaN  
6600              NaN  
6601              NaN  
6602              NaN  
6603              NaN  
6604              NaN  
6605              NaN  
6606              NaN  
6607              NaN

In [11]:
internet_df.tail(10)

Country or Area                                               Year  \
4665             170                   Refers to the total population.    
4666             171                        Internet Dial-up customers.   
4667             172  Population age 16+ using the Internet in the l...   
4668             173  Population age 16+ using internet in the last ...   
4669             174  U.S. Census Bureau, Table 2. Reported Internet...   
4670             175             Includes individuals 3 years and older   
4671             176                                   NTIA/CPS survey.   
4672             178  Estimated based on Survey's results. Populatio...   
4673             179                     Preliminary. Country estimate.   
4674             180  The methodology used to estimated the figure f...   

      Value  Value Footnotes  
4665    NaN              NaN  
4666    NaN              NaN  
4667    NaN              NaN  
4668    NaN              NaN  
4669    NaN              NaN  
4670    NaN              NaN  
4671    NaN              NaN  
4672    NaN              NaN  
4673    NaN              NaN  
4674    NaN              NaN

In [12]:
gdp_df.drop(columns=['Value Footnotes'], axis=1, inplace=True)

In [13]:
internet_df.drop(columns=['Value Footnotes'], axis=1, inplace=True)

In [14]:
gdp_df = gdp_df.rename(columns={'Country or Area': 'Country', 'Value': 'GDP_Per_Capita'})

In [15]:
internet_df = internet_df.rename(columns={'Country or Area': 'Country', 'Value': 'Internet_Users_Pct'})

In [16]:
gdp_df.head()

Country  Year  GDP_Per_Capita
0  Afghanistan  2018     2190.240321
1  Afghanistan  2017     2202.570851
2  Afghanistan  2016     2200.764487
3  Afghanistan  2015     2212.750899
4  Afghanistan  2014     2249.253738

In [17]:
internet_df.head()

Country  Year  Internet_Users_Pct
0  Afghanistan  2014            6.390000
1  Afghanistan  2013            5.900000
2  Afghanistan  2012            5.454545
3  Afghanistan  2011            5.000000
4  Afghanistan  2010            4.000000

### Merge is Here

In [31]:
pd.merge(internet_df, gdp_df, on = 'Country', how='left')

In [31]:
gdp_and_internet_use = pd.merge(internet_df, gdp_df, on = 'Country', how='left')

In [32]:
gdp_and_internet_use.shape

(102866, 5)

In [33]:
gdp_and_internet_use[gdp_and_internet_use["Country"] == "Bermuda"]

Country Year_x  Internet_Users_Pct Year_y  GDP_Per_Capita
10689  Bermuda   2014           96.800000    NaN             NaN
10690  Bermuda   2013           95.300000    NaN             NaN
10691  Bermuda   2012           91.299305    NaN             NaN
10692  Bermuda   2011           88.336000    NaN             NaN
10693  Bermuda   2010           84.210000    NaN             NaN
10694  Bermuda   2009           83.250000    NaN             NaN
10695  Bermuda   2008           82.300000    NaN             NaN
10696  Bermuda   2007           74.350594    NaN             NaN
10697  Bermuda   2006           69.899655    NaN             NaN
10698  Bermuda   2005           65.447066    NaN             NaN
10699  Bermuda   2004           60.990867    NaN             NaN
10700  Bermuda   2003           56.522012    NaN             NaN
10701  Bermuda   2002           52.031597    NaN             NaN
10702  Bermuda   2001           47.509700    NaN             NaN
10703  Bermuda   2000           42.949860    NaN             NaN
10704  Bermuda   1999           39.947589    NaN             NaN
10705  Bermuda   1998           32.103759    NaN             NaN
10706  Bermuda   1997           24.189257    NaN             NaN
10707  Bermuda   1996           16.202466    NaN             NaN
10708  Bermuda   1995            6.838163    NaN             NaN
10709  Bermuda   1990            0.000000    NaN             NaN

In [34]:
gdp_and_internet_use[gdp_and_internet_use['Year_y'].isnull()]

Country                                             Year_x  \
1502    American Samoa                                               1990   
1503           Andorra                                               2014   
1504           Andorra                                               2013   
1505           Andorra                                               2012   
1506           Andorra                                               2011   
...                ...                                                ...   
102861             175             Includes individuals 3 years and older   
102862             176                                   NTIA/CPS survey.   
102863             178  Estimated based on Survey's results. Populatio...   
102864             179                     Preliminary. Country estimate.   
102865             180  The methodology used to estimated the figure f...   

        Internet_Users_Pct Year_y  GDP_Per_Capita  
1502              0.000000    NaN             NaN  
1503             95.900000    NaN             NaN  
1504             94.000000    NaN             NaN  
1505             86.434425    NaN             NaN  
1506             81.000000    NaN             NaN  
...                    ...    ...             ...  
102861                 NaN    NaN             NaN  
102862                 NaN    NaN             NaN  
102863                 NaN    NaN             NaN  
102864                 NaN    NaN             NaN  
102865                 NaN    NaN             NaN  

[1062 rows x 5 columns]

In [35]:
gdp_and_internet_use[gdp_and_internet_use.Country.eq("Germany") & gdp_and_internet_use.Year_y.eq("2000")]

Country Year_x  Internet_Users_Pct Year_y  GDP_Per_Capita
33676  Germany   2014           86.190000   2000    42858.018983
33705  Germany   2013           84.170000   2000    42858.018983
33734  Germany   2012           82.349998   2000    42858.018983
33763  Germany   2011           81.270000   2000    42858.018983
33792  Germany   2010           82.000000   2000    42858.018983
33821  Germany   2009           79.000000   2000    42858.018983
33850  Germany   2008           78.000000   2000    42858.018983
33879  Germany   2007           75.160000   2000    42858.018983
33908  Germany   2006           72.160000   2000    42858.018983
33937  Germany   2005           68.710000   2000    42858.018983
33966  Germany   2004           64.730000   2000    42858.018983
33995  Germany   2003           55.900000   2000    42858.018983
34024  Germany   2002           48.820000   2000    42858.018983
34053  Germany   2001           31.650939   2000    42858.018983
34082  Germany   2000           30.216347   2000    42858.018983
34111  Germany   1999           20.845983   2000    42858.018983
34140  Germany   1998            9.877852   2000    42858.018983
34169  Germany   1997            6.711087   2000    42858.018983
34198  Germany   1996            3.054805   2000    42858.018983
34227  Germany   1995            1.837738   2000    42858.018983
34256  Germany   1994            0.922541   2000    42858.018983
34285  Germany   1993            0.463635   2000    42858.018983
34314  Germany   1992            0.435285   2000    42858.018983
34343  Germany   1991            0.250274   2000    42858.018983
34372  Germany   1990            0.125892   2000    42858.018983

In [ ]:
gdp_and_internet_use.head()

In [ ]:
gdp_and_internet_use.tail()

In [ ]:
# Verified only the last row is dropped
gdp_and_internet_use.dropna(inplace=True)

In [ ]:
gi_subset = gdp_and_internet_use[gdp_and_internet_use["Year"].isin(["2004","2009","2014"])]

In [ ]:
gi_subset.head()

In [ ]:
gi_subset.shape

In [ ]:
gdp_internet_2004_ss = gi_subset[gi_subset["Year"] == "2004"]

In [ ]:
gdp_internet_2009_ss = gi_subset[gi_subset["Year"] == "2009"]

In [ ]:
gdp_internet_2014_ss = gi_subset[gi_subset["Year"] == "2014"]

In [ ]:
gdp_internet_2014_ss[gdp_internet_2014_ss.Internet_Users_Pct == gdp_internet_2014_ss.Internet_Users_Pct.max()]

In [ ]:
gdp_internet_2014_ss[gdp_internet_2014_ss.Internet_Users_Pct == gdp_internet_2014_ss.Internet_Users_Pct.min()]

In [ ]:
gdp_internet_2009_ss[gdp_internet_2009_ss.Internet_Users_Pct == gdp_internet_2009_ss.Internet_Users_Pct.max()]

In [ ]:
gdp_internet_2009_ss[gdp_internet_2009_ss.Internet_Users_Pct == gdp_internet_2009_ss.Internet_Users_Pct.min()]

In [ ]:
gdp_internet_2004_ss[gdp_internet_2004_ss.Internet_Users_Pct == gdp_internet_2004_ss.Internet_Users_Pct.max()]

In [ ]:
gdp_internet_2004_ss[gdp_internet_2004_ss.Internet_Users_Pct == gdp_internet_2004_ss.Internet_Users_Pct.min()]

In [ ]:
gdp_internet_2014_ss[gdp_internet_2014_ss.GDP_Per_Capita == gdp_internet_2014_ss.GDP_Per_Capita.max()]

In [ ]:
gdp_internet_2014_ss[gdp_internet_2014_ss.GDP_Per_Capita == gdp_internet_2014_ss.GDP_Per_Capita.min()]

In [ ]:
plt.scatter(x = 'Internet_Users_Pct', y ='GDP_Per_Capita', data = gdp_internet_2004_ss)
plt.xlabel('Percent Internet Users')
plt.ylabel('GDP per capita')
plt.title('2004 Internet Users Percent vs GDP per capita');

In [ ]:
plt.scatter(x = 'Internet_Users_Pct', y ='GDP_Per_Capita', data = gdp_internet_2009_ss)
plt.xlabel('Percent Internet Users')
plt.ylabel('GDP per capita')
plt.title('2009 Internet Users Percent vs GDP per capita');

In [ ]:
plt.scatter(x = 'Internet_Users_Pct', y ='GDP_Per_Capita', data = gdp_internet_2014_ss)
plt.xlabel('Percent Internet Users')
plt.ylabel('GDP per capita')
plt.title('2014 Internet Users Percent vs GDP per capita');

I found the scatterplots very interesting. In 2004 there was a definite trend line that the higher the GDP the higher the percentage of internet users. The trend from 2004 to 2014, over the next ten years, was a significant flatting on the line. Also there did not seem to be as big of a shift from left to the right of the plot as I would have expected. I guess I can also say there does not also seem to as much of a shift from the bottom of the plot upward as I would have liked to see. Overall I think this indicates a slower rate of internet adoption and of economic growth than one might have hoped for. 

Both percentage of internet use and GDP per capita appear to be unimodal for 2014.

In [ ]:
gdp_internet_2014_ss.nlargest(5, 'Internet_Users_Pct')

In [ ]:
gdp_df[gdp_df["Country"] == "Bermuda"]

In [ ]:
internet_df[internet_df["Country"] == "Bermuda"]

In [ ]:
top_5_internet = pd.concat([gdp_internet_2004_ss.nlargest(5, 'Internet_Users_Pct'), gdp_internet_2009_ss.nlargest(5, 'Internet_Users_Pct'), gdp_internet_2014_ss.nlargest(5, 'Internet_Users_Pct')], axis=0)

In [ ]:
top_5_internet.reset_index(drop=True)

In [ ]:
g = sns.FacetGrid(top_5_internet, col="Year")
g.map(sns.scatterplot, "Internet_Users_Pct", "Country")

In [ ]:
internet_df[internet_df["Country"] == "Bermuda"]

In [ ]:
gdp_internet_2014_ss.nlargest(5, 'Internet_Users_Pct')